### ISSUE TITLE
problem with armory

### ISSUE THREAD

**Issue by bwshood** [AquaFlameCMS/AquaFlameCMS_Trinity#34]
Hi guys i have a litle problem with armory
so i got whis
<a target="_blank" href="http://fastpic.ru"><img src="http://i57.fastpic.ru/big/2014/0408/c5/d9a83e42d27def6e5afe9086ccd96ec5.jpg" border="0"></a>
and i have whis
Fatal error: Cannot redeclare mysql_open() (previously declared in H:\localhost\Winginx\home\localhost\public_html\functions\armory_func.php:5) in H:\localhost\Winginx\home\localhost\public_html\functions\armory_func.php on line 8

**Comment by oneluiz** [comment]
https://github.com/FlameNET
