### ISSUE TITLE
problem with last update

### ISSUE THREAD

**Issue by bwshood** [AquaFlameCMS/AquaFlameCMS_Trinity#40]
Hi every one after update Web/Home: Update Index.php
i see what slideshow doest work
i see when  we telete with
<div id="left">
<script src="<?php echo $website['root']; ?>wow/static/local-common/js/slideshow.js"></script>
<script src="<?php echo $website['root']; ?>wow/static/local-common/js/third-party/swfobject.js"></script>
<div id="slideshow" class="ui-slideshow">
the slideshow dont slide
i solve with problem like that
<?php
require_once("configs.php");
require_once("functions/custom.php");
$page_cat = "home";
?>
<!doctype html>

 <html class="no-js"> 
<HTML>
<head>
	<title><?php echo $website['title']; ?></title>
	<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
	<meta name="viewport" content="width=device-width">
	<meta name="description" content="<?php echo $website['description']; ?>">
    <meta name="keywords" content="<?php echo $website['keywords']; ?>">
	<link rel="shortcut icon" href="<?php echo $website['root']; ?>wow/static/local-common/images/favicons/wow.png" type="image/x-icon">
	<?php GetStyle(); ?>
	<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
	<script src="<?php echo $website['root']; ?>wow/static/local-common/js/third-party/jquery-1.4.4-p1.min.js"></script>
	<script src="<?php echo $website['root']; ?>wow/static/local-common/js/core.js?v15"></script> 
     <script src="<?php echo $website['root']; ?>wow/static/local-common/js/tooltip.js?v15"></script>
	<script src="http://static.wowhead.com/widgets/power.js"></script>
	
	</head>
	<body class="en-us homepage  news" onUnload="opener.location=('index.php')">
<div id="wrapper">
<?php include("header.php"); ?>
<div id="content">
<div class="content-top body-top">
<div class="content-trail">
	<ol class="ui-breadcrumb">
		<li class="last">
			<a href="index.html" rel="np" itemprop="url">
				<span class="breadcrumb-text" itemprop="name"><?php echo $website['title']; ?></span>
			</a>
		</li>
	</ol>
</div>
<div class="content-bot clear">
<script src="<?php echo $website['root']; ?>wow/static/local-common/js/slideshow.js"></script> 
          <script src="<?php echo $website['root']; ?>wow/static/local-common/js/third-party/swfobject.js"></script> 
          <div id="slideshow" class="ui-slideshow"> 
           <div class="slideshow">
			<?php
			$slideshows = mysql_query("SELECT * FROM slideshows ORDER BY id ASC LIMIT 5");
			mysql_error($connection_setup);
			$i=0;
			while($slideshow=mysql_fetch_array($slideshows))
			{
			if($i == 0)
			{
			echo'<div class="slide" id="slide-'.$i.'" style="background-image: url(\'images/slideshows/'.$slideshow['image'].'\'); "></div>';
			}
			if($i != 0)
			{
			echo'<div class="slide" id="slide-'.$i.'" style="background-image: url(\'images/slideshows/'.$slideshow['image'].'\'); display: none;"></div>';
			}
			$i++;
			}
			echo'</div>';
			?>
            <div class="paging">

and in forum blizzard topic dont slide for me

and someone can help me i have problem with vote-history.php error Table 'auth.votes_log' doesn't exist

votes_log must be in site bd
whan i votes_log move to auth and its works but not refresh

**Comment by oneluiz** [comment]
https://github.com/FlameNET
