### ISSUE TITLE
... realy?

### ISSUE THREAD

**Issue by adomasalcore3** [AquaFlameCMS/AquaFlameCMS_Trinity#46]
in line 139 of file armory class:
		switch ($this->getObjectInfo())
		{
			case 1:		$result = array(17,14,15); break;
			case 2: 	$result = array(17,14,28); break;
			case 3:		$result = array(21,22,15); break;
			case 4:		$result = array(21,22,25); break;
			case 8:            *
			case 9:            *
			case 5:		$result = array(21,23,26); break;
			case 11:          *
			case 6:		$result = array(21,22,28); break;
			case 7: 	$result = array(21,22,26); break;
		}
		return $result;
	}

where are the * in original rep file?? code missing?

**Comment by oneluiz** [comment]
https://github.com/FlameNET
