### ISSUE TITLE
problem with armory #2

### ISSUE THREAD

**Issue by bwshood** [AquaFlameCMS/AquaFlameCMS_Trinity#47]
hi guys i noticed with problem that
when i log in i have 
<a target="_blank" href="http://fastpic.ru"><img src="http://i67.fastpic.ru/big/2014/0720/41/3755f30da08fbd6540df05b375bd6341.jpg" border="0"></a>
so when i log off 
<a target="_blank" href="http://fastpic.ru"><img src="http://i66.fastpic.ru/big/2014/0720/f2/6f12a46ffd00cc139a8f2e452531dcf2.jpg" border="0"></a>

**Comment by oneluiz** [comment]
https://github.com/FlameNET
