### ISSUE TITLE
Armoury issue

### ISSUE THREAD

**Issue by wattz79** [AquaFlameCMS/AquaFlameCMS_Trinity#48]
Hi guys wondered if someone could help me please ,i am using xampp and installed aquaflameCMS_trinity but i can not get the armory working after following instructions for it :( 
![screenshot_2](https://cloud.githubusercontent.com/assets/5776990/4123819/e38c2bd4-32d1-11e4-8633-68033f81f1af.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5776990/4123822/ef012258-32d1-11e4-86cf-5c00edb7f3ff.png)

i have changed the armory.class.php user name and password as instructed on AC-Web but still no luck ,some guidance here would be greatly appreciated please

**Comment by oneluiz** [comment]
https://github.com/FlameNET
